# Generated by Django 6.0.2 on 2026-03-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydatabase', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='play_time',
            new_name='best_time',
        ),
    ]
